### ISSUE TITLE
Tor: note on long lived ports & socks authentication?

### ISSUE THREAD

**Issue by Mikaela** [yggdrasil-network/public-peers#73]
I have two suggestions and I am opening this issue so that I remember to create a PR at a better time:

* [ ] Add a note that Tor peers should be using long-lived ports to reduce chance of nodes going down.

> LongLivedPorts PORTS
> A list of ports for services that tend to have long-running connections (e.g. chat and interactive shells). Circuits for streams that use these
> ports will contain only high-uptime nodes, to reduce the chance that a node will go down before the stream is finished. Note that the list is
> also honored for circuits (both client and service side) involving hidden services whose virtual port is in this list. (Default: 21, 22, 706,
> 1863, 5050, 5190, 5222, 5223, 6523, 6667, 6697, 8300)
> ~~ `man torrc`

* ~~Use SOCKS authentication to cause Tor to isolate Yggdrasil traffic from other traffic.~~
    * ~~I guess this could also be used for adding a comment on who is the admin which sanitizing config file wouldn't remove?~~

> IsolateSOCKSAuth
> Don’t share circuits with streams for which different SOCKS authentication was provided. (For HTTPTunnelPort connections, this option looks
> at the Proxy-Authorization and X-Tor-Stream-Isolation headers. On by default; you can disable it with NoIsolateSOCKSAuth.)
> ~~ `man torrc`

~~Yggdrasil may support this by default as so does dnscrypt-proxy?~~

> `socks5://user:password@127.0.0.1:9050` should work. TBH, I haven't tried but the Go SOCK5 client code I use appears to support authentication out of the box.
> https://github.com/jedisct1/dnscrypt-proxy/issues/560#issuecomment-410690494

**Comment by akklesed** [comment]
>Add a note that Tor peers should be using long-lived ports to reduce chance of nodes going down.

Would be good recommendation, yeah.

>I guess this could also be used for adding a comment on who is the admin which sanitizing config file wouldn't remove?

Using different circuits for different peerings wouldn't be useful, because yggdrasil already exposes its identity to neighbours. Could actually be worse for anonimity (because tor client would be making more trivially cross-link-able circuits). I think yggdrasil using its own identity isn't bad idea, though.
For metadata/comment either not sanitizing config on every upgrade, or something like using `tcp://1.2.3.4#nodename,nodeadmin...` would be better idea, I think. Auth/Pass is bad place to hack it in.
I personally just have my own config formatted how I want with comments, and don't allow yggdrasil to reformat it.

>Yggdrasil may support this by default as so does dnscrypt-proxy?

https://github.com/yggdrasil-network/yggdrasil-go/blob/dc3a05f13ab2ea084a6453b0b11915a5458e2ec5/src/yggdrasil/tcp.go#L237-L261
`dialer, err = proxy.SOCKS5("tcp", dialerdst.String(), nil, proxy.Direct)`
So it seems no, `auth` argument is currently hardcoded to nil.

**Comment by Mikaela** [comment]
Thanks, I strikethrouged the proxy authentication parts and opened #74 on the LongLivedPorts.

**Comment by akklesed** [comment]
Well, actually supporting proxy auth wouldn't be bad thing (just don't use separate values for tor peerings).
I think that should be implemented. Probably deserves separate ticket in main repo.

**Comment by Mikaela** [comment]
I will let you take the honour of opening that issue :smiley:
